// web/components/Settings/Settings.tsx
"use client";

import { ReactNode, useState } from "react";
import { Field, Flex, Heading, HStack, Input, NativeSelect, Slider, Stack, Switch } from "@chakra-ui/react";
import { FormattedMessage, useIntl } from "react-intl";
import { ApertureIcon, BellIcon, DivideIcon, GlobeIcon, ImageIcon, PercentIcon } from "lucide-react";
import type { User } from "@/utils/api";
import { Config, useConfig } from "@/utils/config";
import { parseResinButtons, ResinCap } from "@/db/resins";
import { LanguageNames, Languages } from "@/langs";
import ResinNotification from "../Home/ResinNotification";
import { AccountManageButton, ConfigExportButton, SignOutButton } from "./AccountButtons";

const TranslationsUrl = "https://github.com/Seeker14491/genshin-schedule/tree/master/web/langs";

/** Settings page. `user` is only given for signed-in users. */
const Settings = ({ user }: { user?: User | null }) => {
  return (
    <Stack gap={4}>
      <Heading size="xl">
        <FormattedMessage defaultMessage="Settings" />
      </Heading>

      <Stack gap={4} align="start">
        <ThemeSwitch />
        <LanguageSwitch />
        <BackgroundSwitch />
        <ResinEstimateModeSwitch />
        <ResinCalcButtonInput />
        <ResinNotifyMarkSlider />

        <Flex wrap="wrap" gap={2}>
          <ConfigExportButton />
          {user && <AccountManageButton user={user} />}
          <SignOutButton />
        </Flex>
      </Stack>
    </Stack>
  );
};

const SettingLabel = ({ icon, children }: { icon: ReactNode; children: ReactNode }) => (
  <Field.Label fontWeight="medium">
    <HStack gap={2}>
      {icon}
      {children}
    </HStack>
  </Field.Label>
);

const ThemeSwitch = () => {
  const [value, setValue] = useConfig("theme");

  return (
    <Switch.Root
      colorPalette="blue"
      checked={value === "dark"}
      onCheckedChange={({ checked }) => setValue(checked ? "dark" : "light")}
    >
      <Switch.HiddenInput />
      <Stack gap={1.5}>
        <Switch.Label fontWeight="medium">
          <HStack gap={2}>
            <ApertureIcon size="1em" />
            <FormattedMessage defaultMessage="Dark mode" />
          </HStack>
        </Switch.Label>
        <Switch.Control />
      </Stack>
    </Switch.Root>
  );
};

const Select = ({
  value,
  onChange,
  children,
}: {
  value: string;
  onChange: (value: string) => void;
  children: ReactNode;
}) => (
  <NativeSelect.Root maxW="xs">
    <NativeSelect.Field value={value} onChange={(e) => onChange(e.currentTarget.value)}>
      {children}
    </NativeSelect.Field>
    <NativeSelect.Indicator />
  </NativeSelect.Root>
);

const LanguageSwitch = () => {
  const { formatMessage } = useIntl();
  const [value, setValue] = useConfig("language");

  return (
    <Field.Root>
      <SettingLabel icon={<GlobeIcon size="1em" />}>
        <FormattedMessage defaultMessage="Language" />
      </SettingLabel>

      <Select
        value={value}
        onChange={(value) => {
          if (value === "contribute") {
            window.open(TranslationsUrl);
          } else {
            setValue(value as Config["language"]);
          }
        }}
      >
        <option value="default">{formatMessage({ defaultMessage: "Default" })}</option>

        {Languages.map((lang) => (
          <option key={lang} value={lang}>
            {LanguageNames[lang]}
          </option>
        ))}

        <option value="contribute">({formatMessage({ defaultMessage: "Add new language" })})</option>
      </Select>
    </Field.Root>
  );
};

const BackgroundSwitch = () => {
  const { formatMessage } = useIntl();
  const [value, setValue] = useConfig("background");

  return (
    <Field.Root>
      <SettingLabel icon={<ImageIcon size="1em" />}>
        <FormattedMessage defaultMessage="Background" />
      </SettingLabel>

      <Select value={value} onChange={(value) => setValue(value as Config["background"])}>
        <option value="paimon">{formatMessage({ defaultMessage: "Paimon" })}</option>
        <option value="klee">{formatMessage({ defaultMessage: "Klee" })}</option>
        <option value="diluc">{formatMessage({ defaultMessage: "Diluc" })}</option>
        <option value="tartaglia">{formatMessage({ defaultMessage: "Tartaglia" })}</option>
        <option value="zhongli">{formatMessage({ defaultMessage: "Zhongli" })}</option>
        <option value="xiao">{formatMessage({ defaultMessage: "Xiao" })}</option>
        <option value="hutao">{formatMessage({ defaultMessage: "Hu Tao" })}</option>
        <option value="kazuha">{formatMessage({ defaultMessage: "Kazuha" })}</option>
        <option value="ayaka">{formatMessage({ defaultMessage: "Ayaka" })}</option>
        <option value="none">{formatMessage({ defaultMessage: "Disabled" })}</option>
      </Select>
    </Field.Root>
  );
};

const ResinEstimateModeSwitch = () => {
  const { formatMessage } = useIntl();
  const [value, setValue] = useConfig("resinEstimateMode");

  return (
    <Field.Root>
      <SettingLabel icon={<DivideIcon size="1em" />}>
        <FormattedMessage defaultMessage="Resin estimation mode" />
      </SettingLabel>

      <Select value={value} onChange={(value) => setValue(value as Config["resinEstimateMode"])}>
        <option value="time">{formatMessage({ defaultMessage: "Time steps (2h, 4h, 8h…)" })}</option>
        <option value="value">{formatMessage({ defaultMessage: "Value steps (20, 40, 60)" })}</option>
      </Select>
    </Field.Root>
  );
};

const ResinCalcButtonInput = () => {
  const [value, setValue] = useConfig("resinCalcButtons");
  const [text, setText] = useState(() => value.map((v) => (v > 0 ? `+${v}` : `${v}`)).join(", "));

  return (
    <Field.Root>
      <SettingLabel icon={<PercentIcon size="1em" />}>
        <FormattedMessage defaultMessage="Resin calculator buttons" />
      </SettingLabel>

      <Input
        maxW="xs"
        value={text}
        onChange={({ currentTarget: { value } }) => {
          setText(value);
          setValue(parseResinButtons(value));
        }}
      />
    </Field.Root>
  );
};

const ResinNotifyMarkSlider = () => {
  const [value, setValue] = useConfig("resinNotifyMark");

  return (
    <>
      {/* keeps the queued notification up to date with the slider */}
      <ResinNotification />

      <Slider.Root
        colorPalette="blue"
        w="sm"
        maxW="full"
        value={[value]}
        step={10}
        min={10}
        max={ResinCap}
        onValueChange={({ value }) => setValue(value[0])}
      >
        <HStack justify="space-between">
          <Slider.Label fontWeight="medium">
            <HStack gap={2}>
              <BellIcon size="1em" />
              <FormattedMessage defaultMessage="Send resin notification at" />
            </HStack>
          </Slider.Label>
          <Slider.ValueText />
        </HStack>
        <Slider.Control>
          <Slider.Track>
            <Slider.Range />
          </Slider.Track>
          <Slider.Thumbs />
        </Slider.Control>
      </Slider.Root>
    </>
  );
};

export default Settings;

// web/src/lib/components/settings/Settings.svelte
<script lang="ts">
  import { ApertureIcon, BellIcon, DivideIcon, GlobeIcon, ImageIcon, PercentIcon } from "@lucide/svelte";
  import type { User } from "#lib/utils/api.ts";
  import { parseResinButtons, ResinCap } from "#lib/db/resins.ts";
  import { isLanguage, Languages, LanguageNames } from "#lib/languages.ts";
  import type { Config } from "#lib/utils/config.ts";
  import { config } from "#lib/session.svelte.ts";
  import { m } from "#lib/paraglide/messages.js";
  import ResinNotification from "../home/ResinNotification.svelte";
  import ManageDataButton from "./ManageDataButton.svelte";
  import ManageAccountButton from "./ManageAccountButton.svelte";
  import SignOutButton from "./SignOutButton.svelte";
  import Field from "./Field.svelte";
  import Switch from "../ui/Switch.svelte";
  import Select from "../ui/Select.svelte";
  import Slider from "../ui/Slider.svelte";
  import { inputClass } from "../ui/input.ts";

  /** Only given for signed-in users. */
  let { user }: { user: User | null } = $props();

  const backgrounds: [Config["background"], () => string][] = [
    ["paimon", m.paimon],
    ["klee", m.klee],
    ["diluc", m.diluc],
    ["tartaglia", m.tartaglia],
    ["zhongli", m.zhongli],
    ["xiao", m.xiao],
    ["hutao", m.hu_tao],
    ["kazuha", m.kazuha],
    ["ayaka", m.ayaka],
    ["none", m.background_disabled],
  ];

  let resinButtons = $state(config.resinCalcButtons.map((v) => (v > 0 ? `+${v}` : `${v}`)).join(", "));
</script>

<div class="flex flex-col gap-4">
  <h1 class="font-heading text-style-xl font-semibold">{m.settings()}</h1>

  <div class="flex flex-col items-start gap-4">
    <Switch bind:checked={() => config.theme === "dark", (dark) => (config.theme = dark ? "dark" : "light")}>
      {#snippet label()}
        <span class="flex items-center gap-2"><ApertureIcon size="1em" />{m.dark_mode()}</span>
      {/snippet}
    </Switch>

    <Field id="language" icon={GlobeIcon} label={m.language()}>
      <Select
        id="language"
        bind:value={
          () => (isLanguage(config.language) ? config.language : "default"),
          (value) => (config.language = value as Config["language"])
        }
      >
        <option value="default">{m.language_default()}</option>
        {#each Languages as language (language)}
          <option value={language}>{LanguageNames[language]}</option>
        {/each}
      </Select>
    </Field>

    <Field id="background" icon={ImageIcon} label={m.background()}>
      <Select
        id="background"
        bind:value={() => config.background, (value) => (config.background = value as Config["background"])}
      >
        {#each backgrounds as [value, name] (value)}
          <option {value}>{name()}</option>
        {/each}
      </Select>
    </Field>

    <Field id="estimation-mode" icon={DivideIcon} label={m.resin_estimation_mode()}>
      <Select
        id="estimation-mode"
        bind:value={
          () => config.resinEstimateMode, (value) => (config.resinEstimateMode = value as Config["resinEstimateMode"])
        }
      >
        <option value="time">{m.estimation_mode_time()}</option>
        <option value="value">{m.estimation_mode_value()}</option>
      </Select>
    </Field>

    <Field id="resin-buttons" icon={PercentIcon} label={m.resin_calculator_buttons()}>
      <input
        id="resin-buttons"
        class="{inputClass} max-w-xs"
        bind:value={resinButtons}
        oninput={() => (config.resinCalcButtons = parseResinButtons(resinButtons))}
      />
    </Field>

    <!-- keeps the queued notification up to date with the slider -->
    <ResinNotification />

    <Slider
      bind:value={() => config.resinNotifyMark, (value) => (config.resinNotifyMark = value)}
      min={10}
      max={ResinCap}
      step={10}
    >
      {#snippet label()}
        <span class="flex items-center gap-2"><BellIcon size="1em" />{m.notification_threshold()}</span>
      {/snippet}
    </Slider>

    <div class="flex flex-wrap gap-2">
      <ManageDataButton />
      {#if user}
        <ManageAccountButton {user} />
      {/if}
      <SignOutButton />
    </div>
  </div>
</div>
