// web/components/Home/Clock.tsx
"use client";

import { Heading, HStack, Link, Stat } from "@chakra-ui/react";
import { FormattedMessage, useIntl } from "react-intl";
import { ClockIcon } from "lucide-react";
import { getResinRecharge, roundResin } from "@/db/resins";
import { ServerList, useConfig } from "@/utils/config";
import { formatDurationPart, getLargestUnit, getServerResetTime, ServerTimeZones, useServerTime } from "@/utils/time";
import { Tooltip } from "../ui/tooltip";

/** Shows the current time on the selected server and the time until daily reset. */
const Clock = () => {
  return (
    <Stat.Root alignItems="center" textAlign="center">
      <Stat.Label>
        <HStack fontSize="md" gap={2} justify="center">
          <ClockIcon size="1em" />
          <div>
            <FormattedMessage defaultMessage="Time in Teyvat" /> (<ServerText />)
          </div>
        </HStack>
      </Stat.Label>

      <Stat.ValueText my={1}>
        <TimeDisplay />
      </Stat.ValueText>

      <Stat.HelpText>
        <DateDisplay />
      </Stat.HelpText>
    </Stat.Root>
  );
};

const ServerText = () => {
  const [server, setServer] = useConfig("server");
  const { formatMessage } = useIntl();

  const names = {
    America: formatMessage({ defaultMessage: "America" }),
    Europe: formatMessage({ defaultMessage: "Europe" }),
    Asia: formatMessage({ defaultMessage: "Asia" }),
    "TW, HK, MO": formatMessage({ defaultMessage: "TW, HK, MO" }),
  };

  return (
    <Tooltip
      content={
        <>
          <FormattedMessage defaultMessage="Switch server" /> (<code>{ServerTimeZones[server]}</code>)
        </>
      }
      closeOnClick={false}
    >
      <Link
        as="button"
        fontWeight="bold"
        onClick={() => setServer(ServerList[(ServerList.indexOf(server) + 1) % ServerList.length])}
      >
        {names[server]}
      </Link>
    </Tooltip>
  );
};

const TimeDisplay = () => {
  const time = useServerTime(1000);

  return (
    <Heading size={{ base: "3xl", md: "4xl" }} fontVariantNumeric="tabular-nums">
      {time.toFormat("HH:mm:ss")}
    </Heading>
  );
};

const DateDisplay = () => {
  const intl = useIntl();
  const time = useServerTime(1000);

  const resetTime = getServerResetTime(time);
  const resetDue = resetTime.diff(time);
  const resetResins = roundResin(getResinRecharge(resetDue.valueOf()));

  // the current server day is the day before the next reset
  const weekday = resetTime.minus({ days: 1 }).setLocale(intl.locale).toFormat("cccc");

  return (
    <div>
      {weekday},{" "}
      <FormattedMessage
        defaultMessage="{duration} until reset"
        values={{ duration: formatDurationPart(intl, resetDue, getLargestUnit(resetDue)) }}
      />{" "}
      (+
      <FormattedMessage
        defaultMessage="{value, plural, one {# resin} other {# resins}}"
        values={{ value: resetResins }}
      />
      )
    </div>
  );
};

export default Clock;

// web/src/lib/components/home/Clock.svelte
<script lang="ts">
  import { ClockIcon } from "@lucide/svelte";
  import { getResinRecharge, roundResin } from "#lib/db/resin.ts";
  import { ServerList } from "#lib/utils/config.ts";
  import {
    formatDurationPart,
    getLargestUnit,
    getServerResetTime,
    getServerTime,
    ServerTimeZones,
  } from "#lib/utils/time.ts";
  import { config } from "#lib/session.svelte.ts";
  import { clock } from "#lib/clock.svelte.ts";
  import { locale } from "#lib/i18n.svelte.ts";
  import { m } from "#lib/paraglide/messages.js";
  import Tooltip from "../ui/Tooltip.svelte";

  const serverNames = $derived({
    America: m.server_america(),
    Europe: m.server_europe(),
    Asia: m.server_asia(),
    "TW, HK, MO": m.server_tw_hk_mo(),
  });

  const time = $derived(getServerTime(clock.now, config.server));
  const resetTime = $derived(getServerResetTime(time));
  const resetDue = $derived(resetTime.diff(time));

  // the current server day is the day before the next reset
  const weekday = $derived(resetTime.minus({ days: 1 }).setLocale(locale.current).toFormat("cccc"));
</script>

<!-- the current time on the selected server and the time until daily reset -->
<dl class="flex flex-col items-center gap-1 text-center">
  <dt class="flex items-center gap-1.5 text-style-sm text-fg-muted">
    <div class="flex items-center justify-center gap-2 text-md">
      <ClockIcon size="1em" />
      <div>
        {m.time_in_teyvat()} (<Tooltip closeOnClick={false}>
          {#snippet content()}
            {m.switch_server()} (<code>{ServerTimeZones[config.server]}</code>)
          {/snippet}

          <button
            type="button"
            class="link font-bold"
            onclick={() => (config.server = ServerList[(ServerList.indexOf(config.server) + 1) % ServerList.length])}
          >
            {serverNames[config.server]}
          </button>
        </Tooltip>)
      </div>
    </div>
  </dt>

  <dd class="my-1 flex gap-1 text-style-2xl font-semibold tracking-tight">
    <h2 class="font-heading text-style-3xl font-semibold tabular-nums md:text-style-4xl">
      {time.toFormat("HH:mm:ss")}
    </h2>
  </dd>

  <dd class="text-style-xs text-fg-muted">
    {weekday}, {m.until_reset({ duration: formatDurationPart(locale.current, resetDue, getLargestUnit(resetDue)) })}
    ({m.resin_gain({ value: roundResin(getResinRecharge(resetDue.valueOf())) })})
  </dd>
</dl>
