// web/components/Home/ResinNotification.tsx
"use client";

import { useMemo } from "react";
import { useIntl } from "react-intl";
import { DateTime } from "luxon";
import { ResinCap, ResinsPerMinute } from "@/db/resins";
import { useConfig } from "@/utils/config";
import { useApiNotification } from "@/utils/notifications";
import { useServerTime } from "@/utils/time";
import { ResinIcon } from "@/assets";

// color of the Discord message embed
const NotificationColor = "#63b3ed";

/** Queues a Discord notification for when resin reaches the configured amount. */
const ResinNotification = () => {
  const { formatMessage } = useIntl();
  const time = useServerTime(60000);
  const [resin] = useConfig("resin");
  const [notifyMark] = useConfig("resinNotifyMark");

  const capTime = DateTime.fromMillis(resin.time)
    .plus({ minutes: (notifyMark - resin.value) / ResinsPerMinute })
    .valueOf();

  useApiNotification(
    useMemo(
      () => ({
        key: "resin",
        time: capTime,
        icon: ResinIcon.src,
        title: formatMessage({ defaultMessage: "Resin recharged" }),
        description:
          notifyMark === ResinCap
            ? formatMessage({ defaultMessage: "Your resins have fully recharged!" })
            : formatMessage({ defaultMessage: "You have {value} resins right now!" }, { value: notifyMark }),
        url: "/home",
        color: NotificationColor,
      }),
      // the message is only updated when the time changes
      // eslint-disable-next-line react-hooks/exhaustive-deps
      [capTime, notifyMark],
    ),
    time.valueOf() < capTime,
  );

  return null;
};

export default ResinNotification;

// web/src/lib/components/home/ResinNotification.svelte
<script lang="ts">
  import { untrack } from "svelte";
  import { DateTime } from "luxon";
  import { ResinCap, ResinsPerMinute } from "#lib/db/resins.ts";
  import { syncNotification } from "#lib/utils/notifications.svelte.ts";
  import { config } from "#lib/session.svelte.ts";
  import { clock } from "#lib/clock.svelte.ts";
  import { m } from "#lib/paraglide/messages.js";

  // color of the Discord message embed
  const NotificationColor = "#63b3ed";

  /** Time at which resin reaches the notification threshold. */
  const capTime = $derived(
    DateTime.fromMillis(config.resin.time)
      .plus({ minutes: (config.resinNotifyMark - config.resin.value) / ResinsPerMinute })
      .valueOf(),
  );

  const enabled = $derived(clock.minute < capTime);

  // the message is a new object only when the time or threshold changes, which is when the server is updated
  const notification = $derived.by(() => {
    const [time, mark] = [capTime, config.resinNotifyMark];

    return untrack(() => ({
      key: "resin",
      time,
      // a fixed address, so that the icon of notifications queued before a deploy still works
      icon: "/resin.webp",
      title: m.notification_title(),
      description: mark === ResinCap ? m.notification_full() : m.notification_value({ value: mark }),
      url: "/home",
      color: NotificationColor,
    }));
  });

  syncNotification("resin", () => (enabled ? notification : null));
</script>
