// web/components/Notifications/NotificationSetup.tsx
"use client";

import { ReactNode, useSyncExternalStore } from "react";
import NextLink from "next/link";
import { Box, Button, chakra, HStack, Input, InputGroup, Link, Spacer, Stack, useClipboard } from "@chakra-ui/react";
import { FormattedMessage, useIntl } from "react-intl";
import { BellIcon, CheckIcon, CopyIcon, LinkIcon, ListIcon } from "lucide-react";
import { isAuthenticated } from "@/utils/api";
import { getAuthToken } from "@/utils/auth";
import Bot from "@/assets/notifications/Bot.webp";
import Privacy from "@/assets/notifications/Privacy.webp";
import PrivacyDM from "@/assets/notifications/PrivacyDM.webp";
import Success from "@/assets/notifications/Success.webp";
import Panel from "../Panel";
import { Tooltip } from "../ui/tooltip";

export const DiscordBotInvite =
  "https://discord.com/oauth2/authorize?client_id=786827003164098610&scope=bot&permissions=379968";

const linkColor = { base: "blue.500", _dark: "blue.300" };

const Screenshot = ({ src }: { src: string }) => (
  <Box w="max-content" maxW="full">
    <chakra.img src={src} alt="" borderRadius="md" w="40%" minW="xs" maxW="full" />
  </Box>
);

/** Explains how to set up Discord notifications. */
const NotificationSetup = () => {
  const { formatMessage } = useIntl();

  return (
    <Panel divide>
      <HStack gap={2} fontSize="xl" fontWeight="bold">
        <BellIcon size="1em" />
        <div>
          <FormattedMessage defaultMessage="Notifications" />
        </div>

        <Spacer />
        <Tooltip content={formatMessage({ defaultMessage: "Queue" })}>
          <Link asChild color={linkColor} aria-label={formatMessage({ defaultMessage: "Queue" })}>
            <NextLink href="/home/notifications/queue">
              <ListIcon size="0.8em" />
            </NextLink>
          </Link>
        </Tooltip>
      </HStack>

      <Stack gap={4} align="start">
        <div>
          <FormattedMessage
            defaultMessage="Genshin Schedule has a Discord bot that can send you notifications when your resin reaches a certain level (configurable in {settings})."
            values={{
              settings: (
                <Link asChild color={linkColor}>
                  <NextLink href="/settings">
                    <FormattedMessage defaultMessage="Settings" />
                  </NextLink>
                </Link>
              ),
            }}
          />
        </div>

        <Screenshot src={Bot.src} />

        <Step>
          <FormattedMessage defaultMessage="1. Invite the bot to your server. The bot and you need to share a common server in order for the bot to be able to message you." />
          <Button asChild color="white" bg="#7289da" _hover={{ bg: "#677bc4" }}>
            <a href={DiscordBotInvite} target="_blank" rel="noopener noreferrer">
              <LinkIcon />
              <FormattedMessage defaultMessage="Invite the bot" />
            </a>
          </Button>
        </Step>

        <Step>
          <FormattedMessage defaultMessage="2. Make sure DMs from server members are enabled, otherwise the bot cannot message you." />
          <Screenshot src={Privacy.src} />
          <Screenshot src={PrivacyDM.src} />
        </Step>

        <Step>
          <FormattedMessage defaultMessage="3. Copy the following message (you must be signed in) and send it to the bot via DM. Don't share this message with anyone else, ever!" />
          <MessageDisplay />
        </Step>

        <Step>
          <FormattedMessage defaultMessage="The bot should inform you that the process succeeded:" />
          <Screenshot src={Success.src} />
        </Step>
      </Stack>
    </Panel>
  );
};

const Step = ({ children }: { children?: ReactNode }) => (
  <Stack gap={2} align="start" w="full">
    {children}
  </Stack>
);

const subscribeNever = () => () => {};

/** The message to send to the bot, which contains the user's auth token. */
const MessageDisplay = () => {
  const { formatMessage } = useIntl();

  // the token is read from the cookie in the browser so that it isn't included in the server-rendered page
  const token = useSyncExternalStore(subscribeNever, getAuthToken, () => undefined);
  const message = isAuthenticated(token)
    ? `enable ||${token}||`
    : formatMessage({ defaultMessage: "You are not signed in." });

  const clipboard = useClipboard({ value: message });

  return (
    <InputGroup
      w="full"
      startAddon={
        <Button variant="ghost" size="sm" onClick={clipboard.copy}>
          {clipboard.copied ? <CheckIcon /> : <CopyIcon />}
          {clipboard.copied ? <FormattedMessage defaultMessage="Copied" /> : <FormattedMessage defaultMessage="Copy" />}
        </Button>
      }
      startAddonProps={{ px: 1 }}
    >
      <Input readOnly value={message} />
    </InputGroup>
  );
};

export default NotificationSetup;

// web/src/lib/components/notifications/NotificationSetup.svelte
<script lang="ts">
  import { BellIcon, CheckIcon, CopyIcon, LinkIcon } from "@lucide/svelte";
  import { isAuthenticated } from "#lib/utils/api.ts";
  import { getAuthToken } from "#lib/utils/auth.ts";
  import { splitMessage } from "#lib/utils/message.ts";
  import { m } from "#lib/paraglide/messages.js";
  import Bot from "#lib/assets/notifications/Bot.webp";
  import Privacy from "#lib/assets/notifications/Privacy.webp";
  import PrivacyDM from "#lib/assets/notifications/PrivacyDM.webp";
  import Success from "#lib/assets/notifications/Success.webp";
  import Panel from "../Panel.svelte";
  import Button from "../ui/Button.svelte";
  import { inputClass } from "../ui/input.ts";

  const DiscordBotInvite =
    "https://discord.com/oauth2/authorize?client_id=786827003164098610&scope=bot&permissions=379968";

  // the message to send to the bot, which contains the user's auth token
  const token = getAuthToken();
  const message = $derived(isAuthenticated(token) ? `enable ||${token}||` : m.not_signed_in());

  let copied = $state(false);
  let copiedTimeout: ReturnType<typeof setTimeout>;

  async function copy() {
    await navigator.clipboard.writeText(message);

    copied = true;
    clearTimeout(copiedTimeout);
    copiedTimeout = setTimeout(() => (copied = false), 3000);
  }
</script>

{#snippet screenshot(src: string)}
  <div class="w-max max-w-full">
    <img {src} alt="" class="w-2/5 max-w-full min-w-xs rounded-md" />
  </div>
{/snippet}

<!-- explains how to set up Discord notifications -->
<Panel divide>
  <div class="flex items-center gap-2 text-xl font-bold">
    <BellIcon size="1em" />
    <h1>{m.notifications()}</h1>
  </div>

  <div class="flex flex-col items-start gap-4">
    <div>
      {#each splitMessage(m.notifications_intro, ["settings"]) as part, i (i)}
        {#if "text" in part}{part.text}{:else}<a href="/settings" class="link [--link-color:var(--color-link-blue)]"
            >{m.settings()}</a
          >{/if}
      {/each}
    </div>

    {@render screenshot(Bot)}

    <div class="flex w-full flex-col items-start gap-2">
      {m.notifications_step_invite()}

      <Button palette="discord" href={DiscordBotInvite} target="_blank" rel="noopener noreferrer">
        <LinkIcon />
        {m.invite_bot()}
      </Button>
    </div>

    <div class="flex w-full flex-col items-start gap-2">
      {m.notifications_step_privacy()}
      {@render screenshot(Privacy)}
      {@render screenshot(PrivacyDM)}
    </div>

    <div class="flex w-full flex-col items-start gap-2">
      {m.notifications_step_message()}

      <div class="flex w-full">
        <div class="-me-px flex items-center rounded-s-sm border border-border bg-bg-muted px-1 text-style-sm">
          <Button variant="ghost" size="sm" onclick={copy}>
            {#if copied}<CheckIcon />{m.copied()}{:else}<CopyIcon />{m.copy()}{/if}
          </Button>
        </div>

        <input class="{inputClass} rounded-s-none" readonly value={message} aria-label={m.notifications_message()} />
      </div>
    </div>

    <div class="flex w-full flex-col items-start gap-2">
      {m.notifications_step_success()}
      {@render screenshot(Success)}
    </div>
  </div>
</Panel>
