// web/components/Footer.tsx
"use client";

import { HStack, Link, Stack, Text } from "@chakra-ui/react";
import { FormattedMessage, useIntl } from "react-intl";
import { CircleHelpIcon, CommandIcon } from "lucide-react";
import { Tooltip } from "./ui/tooltip";
import { GitHubIcon } from "./ui/icons";
import { HelpUrl } from "./Header";

export const RepositoryUrl = "https://github.com/Seeker14491/genshin-schedule";

const Footer = ({ showShortcuts }: { showShortcuts?: () => void }) => {
  const { formatMessage } = useIntl();
  const linkColor = { base: "pink.500", _dark: "pink.300" };

  return (
    <Stack as="footer" gap={4} p={4} color="gray.500" textAlign="center">
      <Text fontSize="sm">Genshin Schedule is not affiliated with or endorsed by HoYoverse.</Text>

      <Text fontSize="sm">
        <FormattedMessage
          defaultMessage="This site is a fork of the original, now offline, Genshin Schedule. This fork is maintained by {seekr}. The original was written by {chiya} and {contrib}."
          values={{
            seekr: (
              <Link href="https://github.com/Seeker14491" target="_blank" rel="noopener noreferrer" color={linkColor}>
                Seekr
              </Link>
            ),
            chiya: (
              <Link href="https://github.com/chiyadev" target="_blank" rel="noopener noreferrer" color={linkColor}>
                chiya.dev
              </Link>
            ),
            contrib: (
              <Link
                href="https://github.com/chiyadev/genshin-schedule/graphs/contributors"
                target="_blank"
                rel="noopener noreferrer"
                color={linkColor}
              >
                <FormattedMessage defaultMessage="contributors" />
              </Link>
            ),
          }}
        />
      </Text>

      <HStack gap={4} justify="center">
        {showShortcuts && (
          <Tooltip content={formatMessage({ defaultMessage: "Shortcuts" })}>
            <Link as="button" onClick={showShortcuts} aria-label={formatMessage({ defaultMessage: "Shortcuts" })}>
              <CommandIcon size="1em" />
            </Link>
          </Tooltip>
        )}

        <Tooltip content={formatMessage({ defaultMessage: "Help" })}>
          <Link
            href={HelpUrl}
            target="_blank"
            rel="noopener noreferrer"
            aria-label={formatMessage({ defaultMessage: "Help" })}
          >
            <CircleHelpIcon size="1em" />
          </Link>
        </Tooltip>

        <Tooltip content={formatMessage({ defaultMessage: "GitHub" })}>
          <Link href={RepositoryUrl} target="_blank" rel="noopener noreferrer" aria-label="GitHub">
            <GitHubIcon size="1em" />
          </Link>
        </Tooltip>
      </HStack>
    </Stack>
  );
};

export default Footer;

// web/src/lib/components/Footer.svelte
<script lang="ts">
  import { CommandIcon } from "@lucide/svelte";
  import { splitMessage } from "#lib/utils/message.ts";
  import { m } from "#lib/paraglide/messages.js";
  import Tooltip from "./ui/Tooltip.svelte";
  import GitHubIcon from "./ui/GitHubIcon.svelte";

  let { showShortcuts }: { showShortcuts: () => void } = $props();

  const RepositoryUrl = "https://github.com/Seeker14491/genshin-schedule";

  const links = $derived({
    seekr: { href: "https://github.com/Seeker14491", text: "Seekr" },
    chiya: { href: "https://github.com/chiyadev", text: "chiya.dev" },
    contributors: { href: "https://github.com/chiyadev/genshin-schedule/graphs/contributors", text: m.contributors() },
  });
</script>

<footer class="flex flex-col gap-4 p-4 text-center text-gray-500">
  <p class="text-sm">{m.disclaimer()}</p>

  <p class="text-sm [--link-color:var(--color-link-pink)]">
    {#each splitMessage(m.credits, ["seekr", "chiya", "contributors"]) as part, i (i)}
      {#if "text" in part}
        {part.text}
      {:else}
        <a class="link" href={links[part.placeholder].href} target="_blank" rel="noopener noreferrer">
          {links[part.placeholder].text}
        </a>
      {/if}
    {/each}
  </p>

  <div class="flex items-center justify-center gap-4">
    <Tooltip content={m.shortcuts()}>
      <button type="button" class="link" aria-label={m.shortcuts()} onclick={showShortcuts}>
        <CommandIcon size="1em" />
      </button>
    </Tooltip>

    <Tooltip content="GitHub">
      <a class="link" href={RepositoryUrl} target="_blank" rel="noopener noreferrer" aria-label="GitHub">
        <GitHubIcon />
      </a>
    </Tooltip>
  </div>
</footer>
